feat: init projcet
FEMessage/nuxt-modularize pull request #1
Opened 2020-02-20 10:48 UTC by lianghx-319

2020-02-21 04:35 UTC, donaldshen commented on docs/how-to-ues.md
> +# 模块化框架的使用方式
文件名 how-to-use

2020-02-21 04:36 UTC, donaldshen commented on docs/how-to-ues.md
> +- 以域作为划分，所以 demain-{域的描述} 作为模块名
domain

2020-02-21 06:35 UTC, donaldshen commented on docs/how-to-ues.md
> +- **componet 只需要写一个相对路径即可，方便 ide 自动补全路径，增加效率。模块会自动处理文件路径的**
```suggestion
- **component 只需要写一个相对路径即可，方便 ide 自动补全路径，增加效率。模块会自动处理文件路径的**
```

2020-02-25 08:11 UTC, levy9527 requested changes

2020-02-25 08:11 UTC, levy9527 commented on docs/how-to-use.md
> +- 以域作为划分，所以 domain-{域的描述} 作为模块名
为啥是 “以域作为划分”，这里的说话带有太深的业务潜意识了，修改得更中立一点

2020-02-29 07:05 UTC, merged